### ISSUE TITLE
Forma Normal 3

### ISSUE THREAD

**Issue by MarcosRigal** [moruno21/Filmies#1]
Estimado Sr Moruno lamento informarle de que sus tablas no se encuentran normalizadas según la tercera forma normal es por ello que me veo en la obligación de abrir esta issue espero que lo corrija ipsofacto.

Saludos y salud.

**Comment by jdes01** [comment]
JAJSJAJSHJAHSJSH

**Comment by moruno21** [comment]
Querido Marcos, veo que es usted un entendido en bases de datos. Trataré de contentarlo de la mejor manera. El trabajo será efectuado lo antes posible. Que tenga un buen día, cuídese.
